"""add phase9 enterprise foundations

Revision ID: 20260919_0019
Revises: 20260907_0018
Create Date: 2026-09-19 14:54:18.333180
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260919_0019"
down_revision: str | None = "20260907_0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'processed', 'rejected')", name="ck_billing_event_state"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_event_id", name="uq_billing_event_provider"),
    )
    op.create_index(
        op.f("ix_billing_events_workspace_id"), "billing_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "compliance_workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("policy_revision", sa.String(length=80), nullable=False),
        sa.Column("scope_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("authorized_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_manifest", sa.JSON(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('previewed', 'authorized', 'running', 'blocked', 'completed', 'failed')",
            name="ck_compliance_workflow_state",
        ),
        sa.CheckConstraint("length(scope_fingerprint) = 64", name="ck_compliance_scope_hash"),
        sa.ForeignKeyConstraint(["authorized_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_compliance_workflow_key"),
    )
    op.create_index(
        op.f("ix_compliance_workflows_workspace_id"),
        "compliance_workflows",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "connector_installations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("credential_reference", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("checkpoint_cursor", sa.String(length=2000), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('active', 'revoked', 'error')", name="ck_connectors_state"),
        sa.CheckConstraint("revision > 0", name="ck_connectors_revision"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_connectors_id_workspace"),
        sa.UniqueConstraint("workspace_id", "kind", "name", name="uq_connectors_name"),
    )
    op.create_index(
        op.f("ix_connector_installations_workspace_id"),
        "connector_installations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "enterprise_group_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_group_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('admin', 'member', 'viewer')", name="ck_enterprise_group_role"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "provider", "external_group_id", name="uq_enterprise_group"
        ),
    )
    op.create_index(
        op.f("ix_enterprise_group_mappings_workspace_id"),
        "enterprise_group_mappings",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "enterprise_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('active', 'suspended', 'deleted')", name="ck_enterprise_identity_state"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "provider", "external_id", name="uq_enterprise_identity"
        ),
    )
    op.create_index(
        op.f("ix_enterprise_identities_user_id"), "enterprise_identities", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_enterprise_identities_workspace_id"),
        "enterprise_identities",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "entitlement_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_entitlement_policy_version"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "version", name="uq_entitlement_policy_version"),
    )
    op.create_index(
        op.f("ix_entitlement_policies_workspace_id"),
        "entitlement_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "usage_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("meter", sa.String(length=80), nullable=False),
        sa.Column("meter_version", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("correction_of_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("meter_version > 0", name="ck_usage_ledger_meter_version"),
        sa.CheckConstraint("quantity != 0", name="ck_usage_ledger_quantity"),
        sa.ForeignKeyConstraint(
            ["correction_of_id"], ["usage_ledger_entries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_usage_ledger_key"),
    )
    op.create_index(
        op.f("ix_usage_ledger_entries_meter"), "usage_ledger_entries", ["meter"], unique=False
    )
    op.create_index(
        op.f("ix_usage_ledger_entries_workspace_id"),
        "usage_ledger_entries",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "connector_sync_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("base_cursor", sa.String(length=2000), nullable=True),
        sa.Column("proposed_cursor", sa.String(length=2000), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'retry_scheduled', 'succeeded', 'failed', 'cancelled')",
            name="ck_connector_sync_runs_state",
        ),
        sa.CheckConstraint("attempt_count <= max_attempts", name="ck_connector_sync_runs_budget"),
        sa.CheckConstraint("attempt_count >= 0", name="ck_connector_sync_runs_attempts"),
        sa.CheckConstraint("fencing_token >= 0", name="ck_connector_sync_runs_fence"),
        sa.CheckConstraint("max_attempts > 0", name="ck_connector_sync_runs_max_attempts"),
        sa.ForeignKeyConstraint(
            ["connector_id", "workspace_id"],
            ["connector_installations.id", "connector_installations.workspace_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_connector_sync_runs_workspace"),
        sa.UniqueConstraint(
            "workspace_id", "connector_id", "idempotency_key", name="uq_connector_sync_run_key"
        ),
    )
    op.create_index(
        op.f("ix_connector_sync_runs_connector_id"),
        "connector_sync_runs",
        ["connector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_sync_runs_state"), "connector_sync_runs", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_connector_sync_runs_workspace_id"),
        "connector_sync_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "usage_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("meter", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_entry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('active', 'settled', 'released')", name="ck_usage_reservation_state"
        ),
        sa.CheckConstraint("quantity > 0", name="ck_usage_reservation_quantity"),
        sa.ForeignKeyConstraint(
            ["settled_entry_id"], ["usage_ledger_entries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_usage_reservation_key"),
    )
    op.create_index(
        op.f("ix_usage_reservations_workspace_id"),
        "usage_reservations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "connector_source_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("version_external_id", sa.String(length=500), nullable=True),
        sa.Column("permission_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("visibility_state", sa.String(length=16), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("document_version_id", sa.Uuid(), nullable=True),
        sa.Column("last_sequence", sa.String(length=128), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility_state IN ('pending', 'visible', 'denied', 'deleted')",
            name="ck_connector_source_objects_visibility",
        ),
        sa.CheckConstraint("length(permission_fingerprint) = 64", name="ck_source_object_acl_hash"),
        sa.ForeignKeyConstraint(
            ["connector_id", "workspace_id"],
            ["connector_installations.id", "connector_installations.workspace_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "connector_id", "external_id", name="uq_connector_source_object"
        ),
    )
    op.create_index(
        op.f("ix_connector_source_objects_connector_id"),
        "connector_source_objects",
        ["connector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_source_objects_workspace_id"),
        "connector_source_objects",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "connector_sync_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("worker_id", sa.String(length=200), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.CheckConstraint(
            "state IN ('running', 'succeeded', 'retryable_failure', 'permanent_failure', 'lease_expired')",
            name="ck_connector_sync_attempts_state",
        ),
        sa.CheckConstraint("attempt_number > 0", name="ck_connector_sync_attempts_number"),
        sa.CheckConstraint("fencing_token > 0", name="ck_connector_sync_attempts_fence"),
        sa.ForeignKeyConstraint(
            ["run_id", "workspace_id"],
            ["connector_sync_runs.id", "connector_sync_runs.workspace_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "attempt_number", name="uq_connector_sync_attempt_number"),
        sa.UniqueConstraint("run_id", "fencing_token", name="uq_connector_sync_attempt_fence"),
    )
    op.create_index(
        op.f("ix_connector_sync_attempts_run_id"),
        "connector_sync_attempts",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_sync_attempts_workspace_id"),
        "connector_sync_attempts",
        ["workspace_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        _add_postgresql_controls()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_connector_sync_attempts_workspace_id"), table_name="connector_sync_attempts"
    )
    op.drop_index(op.f("ix_connector_sync_attempts_run_id"), table_name="connector_sync_attempts")
    op.drop_table("connector_sync_attempts")
    op.drop_index(
        op.f("ix_connector_source_objects_workspace_id"), table_name="connector_source_objects"
    )
    op.drop_index(
        op.f("ix_connector_source_objects_connector_id"), table_name="connector_source_objects"
    )
    op.drop_table("connector_source_objects")
    op.drop_index(op.f("ix_usage_reservations_workspace_id"), table_name="usage_reservations")
    op.drop_table("usage_reservations")
    op.drop_index(op.f("ix_connector_sync_runs_workspace_id"), table_name="connector_sync_runs")
    op.drop_index(op.f("ix_connector_sync_runs_state"), table_name="connector_sync_runs")
    op.drop_index(op.f("ix_connector_sync_runs_connector_id"), table_name="connector_sync_runs")
    op.drop_table("connector_sync_runs")
    op.drop_index(op.f("ix_usage_ledger_entries_workspace_id"), table_name="usage_ledger_entries")
    op.drop_index(op.f("ix_usage_ledger_entries_meter"), table_name="usage_ledger_entries")
    op.drop_table("usage_ledger_entries")
    op.drop_index(op.f("ix_entitlement_policies_workspace_id"), table_name="entitlement_policies")
    op.drop_table("entitlement_policies")
    op.drop_index(op.f("ix_enterprise_identities_workspace_id"), table_name="enterprise_identities")
    op.drop_index(op.f("ix_enterprise_identities_user_id"), table_name="enterprise_identities")
    op.drop_table("enterprise_identities")
    op.drop_index(
        op.f("ix_enterprise_group_mappings_workspace_id"), table_name="enterprise_group_mappings"
    )
    op.drop_table("enterprise_group_mappings")
    op.drop_index(
        op.f("ix_connector_installations_workspace_id"), table_name="connector_installations"
    )
    op.drop_table("connector_installations")
    op.drop_index(op.f("ix_compliance_workflows_workspace_id"), table_name="compliance_workflows")
    op.drop_table("compliance_workflows")
    op.drop_index(op.f("ix_billing_events_workspace_id"), table_name="billing_events")
    op.drop_table("billing_events")
    # ### end Alembic commands ###


def _add_postgresql_controls() -> None:
    tables = (
        "connector_installations",
        "connector_sync_runs",
        "connector_sync_attempts",
        "connector_source_objects",
        "enterprise_identities",
        "enterprise_group_mappings",
        "entitlement_policies",
        "usage_ledger_entries",
        "usage_reservations",
        "billing_events",
        "compliance_workflows",
    )
    for table in tables:
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON {table} TO mm_rag_api")
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON {table} TO mm_rag_worker")
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO mm_rag_operations")
        expression = (
            "current_setting('mm_rag.purpose', true) = 'operations' OR "
            "(workspace_id = NULLIF(current_setting('mm_rag.workspace_id', true), '')::uuid "
            "AND (mm_rag_is_member(workspace_id) OR "
            "current_setting('mm_rag.purpose', true) = 'worker'))"
        )
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY phase9_scope ON {table} USING ({expression}) WITH CHECK ({expression})"
        )
